spring:
  profiles:
    active: dev
server:
  port: 9000
---
spring:
  profiles: dev
  application:
    name: provider-dev
server:
  port: 9001
---

spring:
  profiles: test
  application:
    name: provider-test-2
server:
  port: 9002    