spring:
  profiles:
    active: dev
server:
  port: 9000
my:
 name: nanmeiying-normal
---
spring:
  profiles: dev
  application:
    name: provider-dev
server:
  port: 9001
my:
 name: nanmeiying-dev-2
---

spring:
  profiles: test
  application:
    name: provider-test
server:
  port: 9002    
my:
 name: nanmeiying-test